import { Driver, Achievement, Reward, Challenge, LeaderboardEntry } from "./types";

export const currentDriver: Driver = {
  id: "1",
  name: "Mike Johnson",
  points: 2450,
  level: 12,
  rank: "Highway Hero",
  streak: 7,
  totalMiles: 45230,
  safetyScore: 98,
  onTimeDeliveries: 156,
  joinedDate: "2024-03-15",
};

export const achievements: Achievement[] = [
  {
    id: "1",
    title: "First Mile",
    description: "Complete your first delivery",
    icon: "road",
    points: 50,
    earned: true,
    earnedDate: "2024-03-16",
  },
  {
    id: "2",
    title: "Safety Star",
    description: "Maintain 100% safety score for 30 days",
    icon: "shield",
    points: 500,
    earned: true,
    earnedDate: "2024-04-20",
  },
  {
    id: "3",
    title: "Iron Horse",
    description: "Drive 10,000 miles without incident",
    icon: "truck",
    points: 1000,
    earned: true,
    earnedDate: "2024-06-10",
  },
  {
    id: "4",
    title: "Early Bird",
    description: "Complete 50 deliveries ahead of schedule",
    icon: "clock-o",
    points: 300,
    earned: false,
    progress: 42,
    maxProgress: 50,
  },
  {
    id: "5",
    title: "Fuel Saver",
    description: "Beat fuel efficiency target for 30 days",
    icon: "leaf",
    points: 400,
    earned: false,
    progress: 18,
    maxProgress: 30,
  },
  {
    id: "6",
    title: "Road Boss",
    description: "Reach the highest rank",
    icon: "crown",
    points: 2000,
    earned: false,
    progress: 2450,
    maxProgress: 7500,
  },
  {
    id: "7",
    title: "Team Player",
    description: "Help 10 fellow drivers",
    icon: "users",
    points: 250,
    earned: false,
    progress: 6,
    maxProgress: 10,
  },
  {
    id: "8",
    title: "Perfect Week",
    description: "Complete all weekly challenges",
    icon: "calendar-check-o",
    points: 350,
    earned: true,
    earnedDate: "2024-08-05",
  },
];

export const rewards: Reward[] = [
  {
    id: "1",
    title: "$25 Amazon Gift Card",
    description: "Redeem for an Amazon gift card",
    icon: "amazon",
    pointsCost: 500,
    category: "gift_card",
    available: true,
  },
  {
    id: "2",
    title: "$50 Gas Card",
    description: "Shell or BP gas card",
    icon: "car",
    pointsCost: 900,
    category: "gift_card",
    available: true,
  },
  {
    id: "3",
    title: "Road Boss Cap",
    description: "Exclusive company merchandise",
    icon: "shopping-bag",
    pointsCost: 300,
    category: "merchandise",
    available: true,
  },
  {
    id: "4",
    title: "Half Day Off",
    description: "Earn a half day of PTO",
    icon: "sun-o",
    pointsCost: 1500,
    category: "time_off",
    available: true,
  },
  {
    id: "5",
    title: "$100 Bonus",
    description: "Cash bonus added to paycheck",
    icon: "money",
    pointsCost: 2000,
    category: "bonus",
    available: true,
  },
  {
    id: "6",
    title: "Premium Parking Spot",
    description: "Reserved spot for 1 month",
    icon: "map-marker",
    pointsCost: 400,
    category: "merchandise",
    available: true,
  },
];

export const challenges: Challenge[] = [
  {
    id: "1",
    title: "Safe Driver",
    description: "Complete 3 deliveries with no incidents",
    points: 50,
    type: "daily",
    progress: 2,
    maxProgress: 3,
    expiresAt: "2024-12-05T23:59:59",
  },
  {
    id: "2",
    title: "On Time Champion",
    description: "Make 5 on-time deliveries",
    points: 75,
    type: "daily",
    progress: 3,
    maxProgress: 5,
    expiresAt: "2024-12-05T23:59:59",
  },
  {
    id: "3",
    title: "Mile Master",
    description: "Drive 500 miles this week",
    points: 200,
    type: "weekly",
    progress: 320,
    maxProgress: 500,
    expiresAt: "2024-12-08T23:59:59",
  },
  {
    id: "4",
    title: "Fuel Efficiency",
    description: "Maintain MPG above target for the week",
    points: 150,
    type: "weekly",
    progress: 5,
    maxProgress: 7,
    expiresAt: "2024-12-08T23:59:59",
  },
];

export const leaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    driver: { id: "5", name: "Sarah Williams", points: 4200, level: 18, rank: "Fleet Captain", streak: 14, totalMiles: 78000, safetyScore: 99, onTimeDeliveries: 234, joinedDate: "2023-08-10" },
    pointsThisPeriod: 580,
  },
  {
    rank: 2,
    driver: { id: "3", name: "James Rodriguez", points: 3800, level: 16, rank: "Fleet Captain", streak: 21, totalMiles: 65000, safetyScore: 97, onTimeDeliveries: 198, joinedDate: "2023-11-20" },
    pointsThisPeriod: 520,
  },
  {
    rank: 3,
    driver: { id: "1", name: "Mike Johnson", points: 2450, level: 12, rank: "Highway Hero", streak: 7, totalMiles: 45230, safetyScore: 98, onTimeDeliveries: 156, joinedDate: "2024-03-15" },
    pointsThisPeriod: 485,
  },
  {
    rank: 4,
    driver: { id: "2", name: "Emily Chen", points: 2100, level: 11, rank: "Highway Hero", streak: 5, totalMiles: 38000, safetyScore: 96, onTimeDeliveries: 142, joinedDate: "2024-01-05" },
    pointsThisPeriod: 410,
  },
  {
    rank: 5,
    driver: { id: "4", name: "David Brown", points: 1850, level: 10, rank: "Highway Hero", streak: 3, totalMiles: 32000, safetyScore: 95, onTimeDeliveries: 128, joinedDate: "2024-02-28" },
    pointsThisPeriod: 380,
  },
  {
    rank: 6,
    driver: { id: "6", name: "Lisa Martinez", points: 1200, level: 8, rank: "Road Runner", streak: 9, totalMiles: 25000, safetyScore: 94, onTimeDeliveries: 95, joinedDate: "2024-05-12" },
    pointsThisPeriod: 295,
  },
  {
    rank: 7,
    driver: { id: "7", name: "Tom Wilson", points: 980, level: 7, rank: "Road Runner", streak: 2, totalMiles: 21000, safetyScore: 92, onTimeDeliveries: 78, joinedDate: "2024-06-01" },
    pointsThisPeriod: 245,
  },
  {
    rank: 8,
    driver: { id: "8", name: "Anna Taylor", points: 650, level: 5, rank: "Road Runner", streak: 4, totalMiles: 15000, safetyScore: 97, onTimeDeliveries: 52, joinedDate: "2024-07-20" },
    pointsThisPeriod: 180,
  },
];
